---
- hosts: all
  become: true

  pre_tasks:
    - name: vars
      ansible.builtin.include_vars: vars.yml

    - name: Check Omada installation status
      ansible.builtin.command: which tpeap
      failed_when: false
      changed_when: false
      check_mode: false
      register: omada_preset

  tasks:
    - name: Uninstall the controller
      ansible.builtin.import_tasks: tasks/uninstall.yml
      when: omada_preset.rc == 0

    - name: Install the controller
      ansible.builtin.import_tasks: tasks/install.yml
