---

- name: is Omada installed
  command: which tpeap
  failed_when: false
  changed_when: false
  check_mode: false
  register: omada_preset

- name: Create Omada Directory "{{ config_dir }}"
  file:
    path: "{{ config_dir }}"
    state: directory
    mode: '0755'

- name: Download & unzip the latest version archive to "{{ config_dir }}"
  unarchive:
    src: "{{ omada_url }}"
    dest: "{{ config_dir }}"
    remote_src: 'yes'
    extra_opts:
      --strip-components=1

- name: make {{ config_dir }}install.sh executable
  file:
    path: "{{ config_dir }}/install.sh"
    mode: a+x

- name: Install Omada
  command: "./install.sh -y -y"
  args:
    chdir: "{{ config_dir }}/"
  register: omadainstall
  when: omada_preset.rc == 1

- name: omada install status
  debug:
    msg: "{{ omadainstall.stdout_lines }}"

- name: Omada install check
  command: which tpeap
  failed_when: false
  changed_when: false
  check_mode: false
  register: omada_done

- name: omada install status
  debug:
    msg: "{{ omada_done.stdout_lines }}"
  when: omada_preset.rc == 1

- name: make sure Omada is running.
  service:
    name: tpeap
    state: started
    enabled: true

- name: Reboot
  reboot:
    post_reboot_delay: 30

- name: Get my public IP
  community.general.ipify_facts:
  register: ip

- name: url
  debug:
    msg: "Omada Controller is running at http://{{ ipify_public_ip }}:8088"
